sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: M8PL1j++aA4UiHhrfmCx0pK31rd+sr6mMIH9um9jNM5yo40MTTTU4fAtSfkBqv+kgTldwNajsVeA7wFg4I5MmyVudSK4lPPbsu0K5OZpW2V9AIU/EjMUvGWENJS26tCFl5+aL+XB09HeTD5TCGJa2QK7Ud3I2LAaLKwVOQ0lrv4x1dlaYZ/30XS31khI8yDvhLa/7/QpDIBWjtuv6bHIl2lH4ooEGABpaEIreScrfsJ38Umwdfzp6TqXXNED1GH4WWSJN4Zm2my1k+It6xtqSN2zLBvOcr7a+sF22T1DhW4t2U0SsZY0Q76j0OqfpkAxzGXKzie5t1p+GKZlyyCpVw/ds7itTyrp4cMltBBsTyjusKvc+v1BHwW6sapFnHBkzbccwPdFRR3Q1oK4VX61NFFaUiDIPNjwHLCMhdSqREBxXfFo/0/KVJNJjEtwzrGBv8wD9d9MpQopLtBS3oHPMbN4lJpvFvm2G6ouTNDauYAmFIi6SS1St9vqgAL/Us2BZmRkIrxO2DJRZJdUxhguoUyeU+82uo6FMU9XJWBGbg2ymi+LCdbUAMAM5xUpyb6+00OCio0V4w0v1Q+tMaYppyqps6LS0t1ZxKo5TSEk7iRAW610gBRNn/hvxWG3TEDgFLKCwZ046SCUwVojkIWK0fqQmnsmR69FhFkRfDKVVHk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Indian-Boyhood_337
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy